version: '3.8'

services:
  react-app:
    build: .
    ports:
      - '3000:80'
    environment:
      - NODE_ENV=production
      - REACT_APP_FAKEUSERS_URL=https://jsonplaceholder.typicode.com/users
      - REACT_APP_FAKEPOSTS_URL=https://jsonplaceholder.typicode.com/posts
